### ISSUE TITLE
Setup ReadTheDocs and properly comment everything.

### ISSUE THREAD

**Issue by bill88t** [bill88t/CircuitPython_AXP313A#1]

**Comment by dhalbert** [comment]
> To override the version included in your build, you can install this driver inside your board's `/` or `/lib`.
Change to:
> To override the version included in your build, you can install this driver inside your board's `/`.

`sys.path` by default is `['', '/', '.frozen', '/lib']`. This means that `.frozen` takes precedence over `/lib`.
